baseURL = 'https://zlh20040308.github.io/'
locale = 'en-US'
title = "Feng's Notes"
theme = 'hugo-ivy'
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = '↩'

[permalinks]
  note = '/note/:slug/'
  post = '/post/:slug/'

[[menu.main]]
  name = 'Home'
  url = '/'
  weight = 1

[[menu.main]]
  name = 'About'
  url = '/about/'
  weight = 2

[[menu.main]]
  name = 'Categories'
  url = '/categories/'
  weight = 3

[[menu.main]]
  name = 'Tags'
  url = '/tags/'
  weight = 4

[params]
  description = "Feng's personal notes"
  footer = '&copy; [Feng](https://github.com/zlh20040308) {Year}'
  highlightjsLang = ['latex', 'python', 'rust', 'nix', 'bash', 'yaml', 'toml', 'json']
  highlightjsTheme = 'github'
  highlightjsVersion = '11.7.0'

[security]
  allowContent = ['.*']

  [security.funcs]
    getenv = ['^HUGO_', '^CI$']

[markup]
  [markup.highlight]
    codeFences = false

  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
